### ISSUE TITLE
Práctica 6

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/practica-de-hilos-SANDRAVELASCO#2]
[Práctica6 Sandra Gabriela Velasco Guzmán.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-SANDRAVELASCO/files/8460968/Practica6.Sandra.Gabriela.Velasco.Guzman.pdf)

**Comment by Yareli-Perez** [comment]
calificación = 80 = 16%

falta descripción, objetivo y lista de figuras 
mas ilustraciones tiene 7 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
